title: Aotu.io - Full Stack Your MAC
subtitle: "Full Stack Your MAC - MAC全栈开发环境搭建指南"
description: "Best installation guide for full-stack developer using MAC OS! MAC全栈开发环境搭建指南"
author: 凹凸实验室(LV&天哥)
language: zh-cn
timezone: UTC
url: http://aotu.io/mac
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:o2team/mac.git
  branch: gh-pages

disqus_shortname:
duoshuo_shortname: aotumac
google_analytics: UA-4910098-10
baidu_analytics: bb4b770d7fdf4e05245cd1327199d813
fb_admins: 100000247608790
swiftype_key: nxhXzi1rDss_9_P_6zBa
twitter: o2circle
github: o2team/mac
gh:
  user: o2team
  repo: mac
